spring:
  application:
    name: minio-demo
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 200MB

server:
  port: 8088

minio:
  endpoint: http://localhost:9001
  accessKey: minio
  secretKey: minio@123456
  nginxHost: http://localhost
